sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HsQ6QnCx375dO05whLlK+aEsPlASBKw+fllCOg8zCFMC/nen3ARfwFP1hs0kuqKDmkUEvAFUnS2E19T1e1R5C6iOMLGF56jF7aWiyWAJQegEDVI+HjhMY0mqTXS8u982UcScRDA6+dnh83yw7PBEmySsETATa8zXoLM9QLoJMqtZu1vfdgdxkiskqc3KpXGRWsUzu0VypUpHIrS/M8z+TfgIMf4rv5ous4A+58TWdKV1WST44W4Y33E1W+AvptgBKThAofblj4NVmwpMsA8/YW6NVaB3mdvARPCLO6ZIOm/4/RyaysWiMdmDJv3DbQScVH+70Bpm+8Q00oUHga3zOZbg0ddjm4Pdrdt0KAV1iTnLeLr5Mood9wFyzQ1p7eYhkGG+/eQwhzdfjWuE7e8AoFKz8PcehjRvWfeFmwrdA7dxNo0ZgWZripheIslRR2uJYlHg2862bQma4n4yuv4ovxRUz7DXTOcz3xhhRByPAs3J/Rpjsb8Lam+apzOVV0bDCAzLzNebjOQoEFZr9fFtu71/Bmrc5Jlf+WKtpQJj8LZgfxYJFA1NPnp6Wcp6mbEnQFj2PtbmW2mc6CA8UPf5DjWOmuc6C2AVVZ639D8wr33Vgdu0QTH0sjUBj10fGBeZ1k1Z831BW2zs7wVhMXPeJ0ROt9JGjZjQ4WwLU5Nwrl0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Germinal_5711
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy